Traceback (most recent call last):
  File "/om2/user/leokoz8/code/rnns-of-rnns/scripts/run_pretrained.py", line 70, in <module>
    dataset = Dataset(envs[task_index], batch_size=64, seq_len=100)
IndexError: list index out of range
Traceback (most recent call last):
  File "/om2/user/leokoz8/code/rnns-of-rnns/scripts/run_pretrained.py", line 70, in <module>
    dataset = Dataset(envs[task_index], batch_size=64, seq_len=100)
IndexError: list index out of range
Traceback (most recent call last):
  File "/om2/user/leokoz8/code/rnns-of-rnns/scripts/run_pretrained.py", line 70, in <module>
    dataset = Dataset(envs[task_index], batch_size=64, seq_len=100)
IndexError: list index out of range
Traceback (most recent call last):
  File "/om2/user/leokoz8/code/rnns-of-rnns/scripts/run_pretrained.py", line 70, in <module>
    dataset = Dataset(envs[task_index], batch_size=64, seq_len=100)
IndexError: list index out of range
Traceback (most recent call last):
  File "/om2/user/leokoz8/code/rnns-of-rnns/scripts/run_pretrained.py", line 70, in <module>
    dataset = Dataset(envs[task_index], batch_size=64, seq_len=100)
IndexError: list index out of range
